# Generated by Django 3.0.7 on 2020-06-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200606_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='platform',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='other_platform',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
