# Generated by Django 3.0.7 on 2020-06-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200606_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='mefi_handle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
