# Generated by Django 3.0.7 on 2020-06-06 13:56

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_myuser_mefi_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
            ],
        ),
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=1000)),
                ('text', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='covers')),
                ('back_image', models.ImageField(blank=True, upload_to='covers')),
                ('tags', models.ManyToManyField(blank=True, to='core.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mix'),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
