# Generated by Django 3.0.7 on 2020-06-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200606_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='other_platform',
        ),
    ]
