# Generated by Django 3.0.7 on 2020-06-27 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200606_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mix',
            name='link',
        ),
    ]
