# Generated by Django 3.0.7 on 2020-06-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_mix_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='group',
            new_name='the_group',
        ),
    ]
