# Generated by Django 3.0.7 on 2020-06-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200628_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Platform'),
        ),
    ]
