# Generated by Django 3.0.7 on 2020-06-28 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_group_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
