# Generated by Django 3.0.8 on 2020-07-08 21:15

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200628_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='mix',
            name='bgcolor',
            field=colorful.fields.RGBColorField(colors=['#9cc754', '#00FF00', '#0000FF'], default='#9cc754', verbose_name='Background color'),
        ),
    ]
