# Generated by Django 3.0.7 on 2020-07-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200708_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mix',
            name='bgcolor',
        ),
        migrations.AddField(
            model_name='mix',
            name='bg_color',
            field=models.CharField(default='#9cc754', max_length=200),
        ),
    ]
