# Generated by Django 3.0.7 on 2020-07-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200709_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='mix',
            name='tx_color',
            field=models.CharField(default='#000000', max_length=200),
        ),
    ]
