# Generated by Django 3.0.7 on 2020-08-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mix_tx_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mix',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
